# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='posted_date',
        ),
    ]
