# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170821_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
